### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by noud** [getcandy/hub#52]
i get lots of error messages like so:
```
$ npm run build

> getcandy-hub@0.12.0 build /home/noud/workspaces/vue/hub
> nuxt build


 WARN  postcss@8.2.10 is installed but ^7.0.32 is expected                 15:32:51


 WARN  sass-loader@8.0.2 is installed but ^10.1.1 is expected              15:32:51

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css       nuxt:tailwindcss 15:32:51
ℹ Merging Tailwind config from ~/tailwind.config.js       nuxt:tailwindcss 15:32:51
ℹ Production build                                                         15:32:52
ℹ Bundling only for client side                                            15:32:52
ℹ Target: static                                                           15:32:52
✔ Builder initialized                                                      15:32:53
✔ Nuxt files generated                                                     15:32:53

✖ Client
  Compiled with some errors in 56.68s


Hash: 1801bfdbb47c54f86308
Version: webpack 4.46.0
Time: 56686ms
Built at: 04/19/2021 3:33:50 PM
                                          Asset       Size  Chunks               Chunk Names
                                     0b44d7d.js   5.84 KiB      25  [immutable]  
                                     0e8fda9.js   2.86 MiB       1  [immutable]  app
                                     10e1705.js   15.6 KiB      12  [immutable]  
                                     2380334.js   1.55 KiB      36  [immutable]  
                                     2cffb30.js   2.72 KiB       4  [immutable]  runtime
                                     327174d.js   12.3 KiB       0  [immutable]  
                                     38ebfeb.js   6.63 KiB      37  [immutable]  
                                     3a233a0.js   7.08 KiB      23  [immutable]  
                                     489e1cb.js   9.34 KiB      14  [immutable]  
                                     4c97e30.js   10.8 KiB      18  [immutable]  
                                     55cc9e1.js   9.84 KiB      28  [immutable]  
                                     5ce9016.js   1.64 KiB      16  [immutable]  
                                     5f3e6ba.js   20.5 KiB      11  [immutable]  
                                     61bea71.js   4.06 KiB      15  [immutable]  
                                     62f747f.js   14.8 KiB      33  [immutable]  
                                     6bd4fdd.js   5.99 KiB       7  [immutable]  
                                     6e92077.js   6.59 KiB      24  [immutable]  
                                     73a632e.js   5.14 KiB      31  [immutable]  
                                     7554a4f.js   5.61 KiB      34  [immutable]  
                                     7605a8a.js   38.9 KiB       5  [immutable]  tailwindConfig/app
                                     76eae86.js   21.2 KiB      22  [immutable]  
                                     7778ad0.js   5.67 KiB      30  [immutable]  
                                     789318a.js  360 bytes       3  [immutable]  pages/unauthorized
                                     797a0f7.js   6.88 KiB      17  [immutable]  
                                     7bd255c.js   2.61 KiB      32  [immutable]  
                                     7e719dc.js   1.67 KiB       9  [immutable]  
                                     8fd05c2.js    1.9 KiB      38  [immutable]  
                                     9092b88.js    256 KiB       2  [immutable]  commons/app
                                     9d6a80d.js   1.45 KiB      29  [immutable]  
                                     9e7053c.js   1.54 KiB      21  [immutable]  
                                       LICENSES   2.62 KiB                       
                                     a478d88.js   14.3 KiB      10  [immutable]  
                                     acafbf3.js   6.31 KiB       8  [immutable]  
                                     b354a0d.js   6.15 KiB      19  [immutable]  
                                     b7f1ef3.js   6.63 KiB      20  [immutable]  
                                     be0d958.js   6.28 KiB      13  [immutable]  
                                     cdba384.js   29.1 KiB      26  [immutable]  
                                     d76f1b6.js   5.67 KiB      35  [immutable]  
                                     da4ab87.js   1.78 KiB       6  [immutable]  
                                     e3e2e8d.js   3.77 KiB      27  [immutable]  
                fonts/Inter-Black.15c8274.woff2    102 KiB                       
                 fonts/Inter-Black.bfea424.woff    137 KiB                       
          fonts/Inter-BlackItalic.158fd1f.woff2    107 KiB                       
           fonts/Inter-BlackItalic.20baa29.woff    142 KiB                       
                 fonts/Inter-Bold.741dc41.woff2    105 KiB                       
                  fonts/Inter-Bold.895ddea.woff    140 KiB                       
           fonts/Inter-BoldItalic.54b6821.woff2    110 KiB                       
            fonts/Inter-BoldItalic.86bc220.woff    146 KiB                       
            fonts/Inter-ExtraBold.3f65bd1.woff2    105 KiB                       
             fonts/Inter-ExtraBold.568245c.woff    140 KiB                       
      fonts/Inter-ExtraBoldItalic.0d568aa.woff2    110 KiB                       
       fonts/Inter-ExtraBoldItalic.a7bb206.woff    146 KiB                       
      fonts/Inter-ExtraLight-BETA.9c975ca.woff2    107 KiB                       
       fonts/Inter-ExtraLight-BETA.caa9496.woff    143 KiB                       
fonts/Inter-ExtraLightItalic-BETA.29e85e0.woff2    113 KiB                       
 fonts/Inter-ExtraLightItalic-BETA.d5ea766.woff    149 KiB                       
               fonts/Inter-Italic.449b5a3.woff2    105 KiB                       
                fonts/Inter-Italic.c4d61b7.woff    139 KiB                       
           fonts/Inter-Light-BETA.5f9d6b2.woff2    106 KiB                       
            fonts/Inter-Light-BETA.8a49915.woff    141 KiB                       
     fonts/Inter-LightItalic-BETA.de35802.woff2    112 KiB                       
      fonts/Inter-LightItalic-BETA.faed878.woff    147 KiB                       
                fonts/Inter-Medium.592a30d.woff    139 KiB                       
               fonts/Inter-Medium.900f310.woff2    104 KiB                       
         fonts/Inter-MediumItalic.1895fa2.woff2    110 KiB                       
          fonts/Inter-MediumItalic.afed191.woff    146 KiB                       
               fonts/Inter-Regular.41cd706.woff    131 KiB                       
              fonts/Inter-Regular.77812e2.woff2   97.7 KiB                       
             fonts/Inter-SemiBold.3d01180.woff2    105 KiB                       
              fonts/Inter-SemiBold.8a12c70.woff    140 KiB                       
       fonts/Inter-SemiBoldItalic.3d40b59.woff2    110 KiB                       
        fonts/Inter-SemiBoldItalic.7e16c47.woff    146 KiB                       
             fonts/Inter-Thin-BETA.a493fa5.woff    142 KiB                       
            fonts/Inter-Thin-BETA.be75564.woff2    108 KiB                       
      fonts/Inter-ThinItalic-BETA.3c5ed4d.woff2    114 KiB                       
       fonts/Inter-ThinItalic-BETA.6ec9551.woff    149 KiB                       
           fonts/Inter-italic.var.f86d3fe.woff2    233 KiB                       
            fonts/Inter-roman.var.4b3800c.woff2    219 KiB                       
                  fonts/Inter.var.feca908.woff2    300 KiB                       
                    fonts/remixicon.31d2848.eot    394 KiB                       
                   fonts/remixicon.881fbc4.woff    169 KiB                       
                    fonts/remixicon.888e61f.ttf    394 KiB                       
                  fonts/remixicon.9915fef.woff2    122 KiB                       
                      img/remixicon.95138f3.svg   1.14 MiB                       
                      img/sweet-jar.4a3bd4b.jpg   94.9 KiB                       
Entrypoint app = 2cffb30.js 9092b88.js 7605a8a.js 0e8fda9.js

ERROR in ./assets/css/app.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/app.scss)
Module not found: Error: Can't resolve './@uppy/core/dist/style.css' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/app.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/app.scss) 4:40-266
 @ ./assets/css/app.scss
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/app.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/app.scss)
Module not found: Error: Can't resolve './@uppy/drag-drop/dist/style.css' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/app.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/app.scss) 5:40-271
 @ ./assets/css/app.scss
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css)
Module not found: Error: Can't resolve './tailwindcss/base' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css) 3:40-196
 @ ./assets/css/tailwind.css
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css)
Module not found: Error: Can't resolve './tailwindcss/components' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css) 4:40-202
 @ ./assets/css/tailwind.css
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css)
Module not found: Error: Can't resolve './tailwindcss/utilities' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css) 5:40-201
 @ ./assets/css/tailwind.css
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error                                                   15:33:50

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Generator.initiate (node_modules/@nuxt/generator/dist/generator.js:110:7)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:71:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:106:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getcandy-hub@0.12.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getcandy-hub@0.12.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noud/.npm/_logs/2021-04-19T13_33_50_866Z-debug.log
```
what to do now?

**Comment by alecritson** [comment]
Can you try using [yarn](https://yarnpkg.com/) and see if that fixes the issue.

**Comment by noud** [comment]
i get the same result:
```
$ yarn run build
yarn run v1.22.5
$ nuxt build

 WARN  postcss@8.2.10 is installed but ^7.0.32 is expected                                                 16:16:06


 WARN  sass-loader@8.0.2 is installed but ^10.1.1 is expected                                              16:16:06

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                       nuxt:tailwindcss 16:16:06
ℹ Merging Tailwind config from ~/tailwind.config.js                                       nuxt:tailwindcss 16:16:07
ℹ Production build                                                                                         16:16:08
ℹ Bundling only for client side                                                                            16:16:08
ℹ Target: static                                                                                           16:16:08
✔ Builder initialized                                                                                      16:16:08
✔ Nuxt files generated                                                                                     16:16:08

✖ Client
  Compiled with some errors in 57.81s


Hash: 1801bfdbb47c54f86308
Version: webpack 4.46.0
Time: 57817ms
Built at: 04/19/2021 4:17:07 PM
                                          Asset       Size  Chunks               Chunk Names
                                     0b44d7d.js   5.84 KiB      25  [immutable]  
                                     0e8fda9.js   2.86 MiB       1  [immutable]  app
                                     10e1705.js   15.6 KiB      12  [immutable]  
                                     2380334.js   1.55 KiB      36  [immutable]  
                                     2cffb30.js   2.72 KiB       4  [immutable]  runtime
                                     327174d.js   12.3 KiB       0  [immutable]  
                                     38ebfeb.js   6.63 KiB      37  [immutable]  
                                     3a233a0.js   7.08 KiB      23  [immutable]  
                                     489e1cb.js   9.34 KiB      14  [immutable]  
                                     4c97e30.js   10.8 KiB      18  [immutable]  
                                     55cc9e1.js   9.84 KiB      28  [immutable]  
                                     5ce9016.js   1.64 KiB      16  [immutable]  
                                     5f3e6ba.js   20.5 KiB      11  [immutable]  
                                     61bea71.js   4.06 KiB      15  [immutable]  
                                     62f747f.js   14.8 KiB      33  [immutable]  
                                     6bd4fdd.js   5.99 KiB       7  [immutable]  
                                     6e92077.js   6.59 KiB      24  [immutable]  
                                     73a632e.js   5.14 KiB      31  [immutable]  
                                     7554a4f.js   5.61 KiB      34  [immutable]  
                                     7605a8a.js   38.9 KiB       5  [immutable]  tailwindConfig/app
                                     76eae86.js   21.2 KiB      22  [immutable]  
                                     7778ad0.js   5.67 KiB      30  [immutable]  
                                     789318a.js  360 bytes       3  [immutable]  pages/unauthorized
                                     797a0f7.js   6.88 KiB      17  [immutable]  
                                     7bd255c.js   2.61 KiB      32  [immutable]  
                                     7e719dc.js   1.67 KiB       9  [immutable]  
                                     8fd05c2.js    1.9 KiB      38  [immutable]  
                                     9092b88.js    256 KiB       2  [immutable]  commons/app
                                     9d6a80d.js   1.45 KiB      29  [immutable]  
                                     9e7053c.js   1.54 KiB      21  [immutable]  
                                       LICENSES   2.62 KiB                       
                                     a478d88.js   14.3 KiB      10  [immutable]  
                                     acafbf3.js   6.31 KiB       8  [immutable]  
                                     b354a0d.js   6.15 KiB      19  [immutable]  
                                     b7f1ef3.js   6.63 KiB      20  [immutable]  
                                     be0d958.js   6.28 KiB      13  [immutable]  
                                     cdba384.js   29.1 KiB      26  [immutable]  
                                     d76f1b6.js   5.67 KiB      35  [immutable]  
                                     da4ab87.js   1.78 KiB       6  [immutable]  
                                     e3e2e8d.js   3.77 KiB      27  [immutable]  
                fonts/Inter-Black.15c8274.woff2    102 KiB                       
                 fonts/Inter-Black.bfea424.woff    137 KiB                       
          fonts/Inter-BlackItalic.158fd1f.woff2    107 KiB                       
           fonts/Inter-BlackItalic.20baa29.woff    142 KiB                       
                 fonts/Inter-Bold.741dc41.woff2    105 KiB                       
                  fonts/Inter-Bold.895ddea.woff    140 KiB                       
           fonts/Inter-BoldItalic.54b6821.woff2    110 KiB                       
            fonts/Inter-BoldItalic.86bc220.woff    146 KiB                       
            fonts/Inter-ExtraBold.3f65bd1.woff2    105 KiB                       
             fonts/Inter-ExtraBold.568245c.woff    140 KiB                       
      fonts/Inter-ExtraBoldItalic.0d568aa.woff2    110 KiB                       
       fonts/Inter-ExtraBoldItalic.a7bb206.woff    146 KiB                       
      fonts/Inter-ExtraLight-BETA.9c975ca.woff2    107 KiB                       
       fonts/Inter-ExtraLight-BETA.caa9496.woff    143 KiB                       
fonts/Inter-ExtraLightItalic-BETA.29e85e0.woff2    113 KiB                       
 fonts/Inter-ExtraLightItalic-BETA.d5ea766.woff    149 KiB                       
               fonts/Inter-Italic.449b5a3.woff2    105 KiB                       
                fonts/Inter-Italic.c4d61b7.woff    139 KiB                       
           fonts/Inter-Light-BETA.5f9d6b2.woff2    106 KiB                       
            fonts/Inter-Light-BETA.8a49915.woff    141 KiB                       
     fonts/Inter-LightItalic-BETA.de35802.woff2    112 KiB                       
      fonts/Inter-LightItalic-BETA.faed878.woff    147 KiB                       
                fonts/Inter-Medium.592a30d.woff    139 KiB                       
               fonts/Inter-Medium.900f310.woff2    104 KiB                       
         fonts/Inter-MediumItalic.1895fa2.woff2    110 KiB                       
          fonts/Inter-MediumItalic.afed191.woff    146 KiB                       
               fonts/Inter-Regular.41cd706.woff    131 KiB                       
              fonts/Inter-Regular.77812e2.woff2   97.7 KiB                       
             fonts/Inter-SemiBold.3d01180.woff2    105 KiB                       
              fonts/Inter-SemiBold.8a12c70.woff    140 KiB                       
       fonts/Inter-SemiBoldItalic.3d40b59.woff2    110 KiB                       
        fonts/Inter-SemiBoldItalic.7e16c47.woff    146 KiB                       
             fonts/Inter-Thin-BETA.a493fa5.woff    142 KiB                       
            fonts/Inter-Thin-BETA.be75564.woff2    108 KiB                       
      fonts/Inter-ThinItalic-BETA.3c5ed4d.woff2    114 KiB                       
       fonts/Inter-ThinItalic-BETA.6ec9551.woff    149 KiB                       
           fonts/Inter-italic.var.f86d3fe.woff2    233 KiB                       
            fonts/Inter-roman.var.4b3800c.woff2    219 KiB                       
                  fonts/Inter.var.feca908.woff2    300 KiB                       
                    fonts/remixicon.31d2848.eot    394 KiB                       
                   fonts/remixicon.881fbc4.woff    169 KiB                       
                    fonts/remixicon.888e61f.ttf    394 KiB                       
                  fonts/remixicon.9915fef.woff2    122 KiB                       
                      img/remixicon.95138f3.svg   1.14 MiB                       
                      img/sweet-jar.4a3bd4b.jpg   94.9 KiB                       
Entrypoint app = 2cffb30.js 9092b88.js 7605a8a.js 0e8fda9.js

ERROR in ./assets/css/app.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/app.scss)
Module not found: Error: Can't resolve './@uppy/core/dist/style.css' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/app.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/app.scss) 4:40-266
 @ ./assets/css/app.scss
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/app.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/app.scss)
Module not found: Error: Can't resolve './@uppy/drag-drop/dist/style.css' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/app.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/app.scss) 5:40-271
 @ ./assets/css/app.scss
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css)
Module not found: Error: Can't resolve './tailwindcss/base' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css) 3:40-196
 @ ./assets/css/tailwind.css
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css)
Module not found: Error: Can't resolve './tailwindcss/components' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css) 4:40-202
 @ ./assets/css/tailwind.css
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css)
Module not found: Error: Can't resolve './tailwindcss/utilities' in '/home/noud/workspaces/vue/hub/assets/css'
 @ ./assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./assets/css/tailwind.css) 5:40-201
 @ ./assets/css/tailwind.css
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                   16:17:07

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Generator.initiate (node_modules/@nuxt/generator/dist/generator.js:110:7)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:71:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:106:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alecritson** [comment]
We recommend using yarn, although we have made some updates to the core packages. Try updating to `0.12.9` you should be able to run `yarn upgrade` to bring everything up.

**Comment by alecritson** [comment]
closing this for lack of activity, if you still have the issue on `0.12.11` then please re open
